# fullsend organization configuration
# https://github.com/fullsend-ai/fullsend
#
# This file is managed by fullsend. Manual edits may be overwritten.
version: "1"
dispatch:
    platform: github-actions
    mode: oidc-mint
inference:
    provider: vertex
defaults:
    roles:
        - fullsend
        - triage
        - coder
        - review
        - retro
        - prioritize
    runtime: claude
    max_implementation_retries: 2
    auto_merge: false
repos:
    .fullsend:
        enabled: false
    agents:
        enabled: true
    experiments:
        enabled: true
    fullsend:
        enabled: true
    metrics:
        enabled: true
allowed_remote_resources:
    - https://raw.githubusercontent.com/fullsend-ai/fullsend/
    - https://raw.githubusercontent.com/fullsend-ai/agents/
create_issues:
    allow_targets:
        orgs:
            - fullsend-ai
        repos:
            - fullsend-ai/fullsend
agents:
  - name: triage
    source: harness/triage-custom.yaml
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/3760b3bb70de32596c1922332fb96e76cd9ebcd8/harness/code.yaml#sha256=274fe0bdce424881a8b2b01a86395a4224c28984fc5863345bcfc424729dac2a
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/3760b3bb70de32596c1922332fb96e76cd9ebcd8/harness/fix.yaml#sha256=1e8aedeb8bbfe24d8f94b938c2c9573ab1196731e67b74cd0c52c7831e1fae69
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/3760b3bb70de32596c1922332fb96e76cd9ebcd8/harness/review.yaml#sha256=6b5cd38510ffe0526c46d8172371e9602634254841abe3e8a8e0ce183d9ef7b9
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/3760b3bb70de32596c1922332fb96e76cd9ebcd8/harness/retro.yaml#sha256=8be74d42aa94ed0083fd1a915f9903435d797b801b3866acd7e8249830388835
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/3760b3bb70de32596c1922332fb96e76cd9ebcd8/harness/prioritize.yaml#sha256=21cf62dce54fce3ae23cf5e3dfe901d03b69bc5e91533288ffa772187b24e95d
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/3760b3bb70de32596c1922332fb96e76cd9ebcd8/harness/scribe.yaml#sha256=1af9dc0123b24ca0a0a13b2292d8818b77d0842efa203268847fa9d4d458ae5a
